/**
 * Local Neuriy agent — capable chat when ElloFive is unreachable.
 * Handles: normal talk, HTML pages, SVG images, multi-step tasks, live topics.
 * Inspired by FRC7 packages/neuriy localGenerate, extended for ChatBase UX.
 */

export type AgentArtifact = {
  type: "html" | "svg" | "markdown" | "task_plan";
  title: string;
  content: string;
  filename?: string;
};

export type AgentResult = {
  reply: string;
  artifacts: AgentArtifact[];
  intent: string;
  provider: "neuriy-local-agent";
};

type Intent =
  | "greet"
  | "html"
  | "image"
  | "task"
  | "live"
  | "code"
  | "marketplace"
  | "chat";

export function detectIntent(text: string): Intent {
  const t = text.toLowerCase();
  if (/^(hi|hello|hey|hoi|hallo|bonjour|salut)\b[.!?\s]*$/i.test(t.trim())) {
    return "greet";
  }
  if (
    /\b(html\s*page|web\s*page|landing\s*page|make\s+(a\s+)?(page|website|site)|create\s+(a\s+)?(page|website|html)|build\s+(a\s+)?(page|website))\b/i.test(
      t
    )
  ) {
    return "html";
  }
  if (
    /\b(image|img|picture|illustration|svg|draw|logo|icon|generate\s+(an?\s+)?(image|picture|drawing))\b/i.test(
      t
    )
  ) {
    return "image";
  }
  if (
    /\b(live|news|today|current|right\s+now|happening|weather|stock|crypto|breaking)\b/i.test(
      t
    )
  ) {
    return "live";
  }
  if (
    /\b(task|todo|plan|steps|how\s+do\s+i|help\s+me\s+(do|build|setup|fix)|checklist)\b/i.test(
      t
    )
  ) {
    return "task";
  }
  if (
    /\b(code|function|typescript|javascript|python|bug|refactor|api\s+route)\b/i.test(
      t
    )
  ) {
    return "code";
  }
  if (/\b(marketplace|neuriy\s+apps?|find\s+app|catalog)\b/i.test(t)) {
    return "marketplace";
  }
  return "chat";
}

function topicFrom(prompt: string): string {
  const cleaned = prompt
    .replace(
      /\b(please|can you|could you|make|create|generate|build|draw|write|me|an?|the|a)\b/gi,
      " "
    )
    .replace(/\s+/g, " ")
    .trim();
  return cleaned.slice(0, 80) || "Neuriy";
}

function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildHtmlPage(prompt: string): AgentArtifact {
  const title = topicFrom(prompt);
  const safe = escapeHtml(title);
  const content = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${safe}</title>
  <style>
    :root {
      --bg: #0f1419;
      --fg: #e8eef4;
      --accent: #3dd6c6;
      --muted: #8b9aab;
      --card: #1a222c;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: "Segoe UI", system-ui, sans-serif;
      background: radial-gradient(1200px 600px at 10% -10%, #1c3a3a 0%, var(--bg) 55%);
      color: var(--fg);
      min-height: 100vh;
    }
    header {
      padding: 2.5rem 1.5rem 1rem;
      max-width: 880px;
      margin: 0 auto;
    }
    .brand {
      font-size: 0.75rem;
      letter-spacing: 0.18em;
      text-transform: uppercase;
      color: var(--accent);
      margin-bottom: 0.75rem;
    }
    h1 {
      font-size: clamp(2rem, 5vw, 3rem);
      line-height: 1.1;
      margin: 0 0 0.75rem;
    }
    .lede { color: var(--muted); max-width: 40rem; }
    main {
      max-width: 880px;
      margin: 0 auto;
      padding: 1rem 1.5rem 3rem;
      display: grid;
      gap: 1rem;
    }
    .panel {
      background: color-mix(in srgb, var(--card) 90%, transparent);
      border: 1px solid #2a3542;
      border-radius: 18px;
      padding: 1.25rem 1.35rem;
    }
    .panel h2 { margin: 0 0 0.5rem; font-size: 1.05rem; }
    .panel p { margin: 0; color: var(--muted); line-height: 1.55; }
    .cta {
      display: inline-block;
      margin-top: 1.25rem;
      padding: 0.75rem 1.2rem;
      border-radius: 999px;
      background: var(--accent);
      color: #04201c;
      font-weight: 700;
      text-decoration: none;
    }
    footer {
      text-align: center;
      color: var(--muted);
      font-size: 0.8rem;
      padding: 2rem 1rem;
    }
  </style>
</head>
<body>
  <header>
    <div class="brand">Neuriy · generated page</div>
    <h1>${safe}</h1>
    <p class="lede">
      This page was generated by Neuriy AI from your request.
      Edit the copy, colors, and sections to match your brand.
    </p>
    <a class="cta" href="#next">Get started</a>
  </header>
  <main id="next">
    <section class="panel">
      <h2>What this is</h2>
      <p>A clean, single-file HTML starter you can open in any browser or drop into your project.</p>
    </section>
    <section class="panel">
      <h2>Your prompt</h2>
      <p>${escapeHtml(prompt.slice(0, 400))}</p>
    </section>
    <section class="panel">
      <h2>Next steps</h2>
      <p>Replace the hero text, add your CTA destination, and ship. Ask Neuriy to refine layout, add forms, or generate matching SVG art.</p>
    </section>
  </main>
  <footer>Built by Neuriy ChatBase · ${new Date().toISOString().slice(0, 10)}</footer>
</body>
</html>`;

  return {
    type: "html",
    title: `${title} — HTML page`,
    filename: `${slugify(title)}.html`,
    content,
  };
}

function buildSvgImage(prompt: string): AgentArtifact {
  const title = topicFrom(prompt);
  const safe = escapeHtml(title.slice(0, 40));
  const hue = (title.length * 37) % 360;
  const content = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="640" viewBox="0 0 1024 640" role="img" aria-label="${safe}">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="hsl(${hue}, 42%, 18%)"/>
      <stop offset="100%" stop-color="hsl(${(hue + 40) % 360}, 35%, 10%)"/>
    </linearGradient>
    <radialGradient id="glow" cx="30%" cy="25%" r="55%">
      <stop offset="0%" stop-color="hsl(${(hue + 20) % 360}, 70%, 62%)" stop-opacity="0.85"/>
      <stop offset="100%" stop-color="hsl(${hue}, 40%, 20%)" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="1024" height="640" fill="url(#bg)"/>
  <circle cx="280" cy="180" r="220" fill="url(#glow)"/>
  <g transform="translate(560 180)">
    <circle r="86" fill="none" stroke="hsl(${(hue + 30) % 360}, 70%, 70%)" stroke-width="10"/>
    <circle r="48" fill="hsl(${(hue + 30) % 360}, 65%, 58%)"/>
    <path d="M-120 140 Q0 40 120 140" fill="none" stroke="hsl(${(hue + 50) % 360}, 55%, 72%)" stroke-width="14" stroke-linecap="round"/>
  </g>
  <text x="64" y="520" fill="#f4f7fb" font-family="Segoe UI, system-ui, sans-serif" font-size="42" font-weight="700">${safe}</text>
  <text x="64" y="562" fill="#a9b7c7" font-family="Segoe UI, system-ui, sans-serif" font-size="20">Neuriy AI · SVG illustration</text>
</svg>`;

  return {
    type: "svg",
    title: `${title} — SVG image`,
    filename: `${slugify(title)}.svg`,
    content,
  };
}

function buildTaskPlan(prompt: string): AgentArtifact {
  const title = topicFrom(prompt);
  const steps = [
    `Clarify the goal: ${title}`,
    "List constraints (time, tools, audience).",
    "Break work into 3–7 concrete actions.",
    "Do the first action immediately (draft / generate / research).",
    "Review output, then iterate or hand off.",
  ];
  const content = [
    `# Task plan: ${title}`,
    "",
    `Request: ${prompt}`,
    "",
    ...steps.map((s, i) => `${i + 1}. ${s}`),
    "",
    "## Done when",
    `- You have a usable artifact or clear next owner for “${title}”.`,
  ].join("\n");

  return {
    type: "task_plan",
    title: `Task plan — ${title}`,
    filename: `${slugify(title)}-plan.md`,
    content,
  };
}

async function fetchLiveBrief(prompt: string): Promise<string> {
  const now = new Date().toUTCString();
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), 4000);
    // Use Wikipedia "on this day" / most-read as a live-ish public feed
    const day = new Date();
    const mm = String(day.getUTCMonth() + 1).padStart(2, "0");
    const dd = String(day.getUTCDate()).padStart(2, "0");
    const res = await fetch(
      `https://en.wikipedia.org/api/rest_v1/feed/featured/${day.getUTCFullYear()}/${mm}/${dd}`,
      {
        signal: ctrl.signal,
        headers: {
          Accept: "application/json",
          "User-Agent": "NeuriyChatBase/1.0 (integration-test)",
        },
      }
    );
    clearTimeout(t);
    if (res.ok) {
      const data = (await res.json()) as {
        tfa?: { title?: string; extract?: string };
        mostread?: { articles?: Array<{ title?: string; extract?: string }> };
        news?: Array<{ links?: Array<{ title?: string }> }>;
      };
      const tfa = data.tfa;
      const top = (data.mostread?.articles || []).slice(0, 3);
      const newsTitles = (data.news || [])
        .flatMap((n) => n.links || [])
        .map((l) => l.title)
        .filter(Boolean)
        .slice(0, 5);

      const parts = [
        `Live brief · ${now}`,
        "",
        `You asked about: “${prompt.slice(0, 160)}”`,
        "",
      ];
      if (tfa?.title) {
        parts.push(
          `**Featured today:** ${tfa.title}`,
          (tfa.extract || "").slice(0, 320),
          ""
        );
      }
      if (top.length) {
        parts.push("**Trending reads:**");
        for (const a of top) {
          parts.push(
            `- ${a.title}: ${(a.extract || "").slice(0, 140)}`
          );
        }
        parts.push("");
      }
      if (newsTitles.length) {
        parts.push(
          "**In the news (Wikipedia feed):** " + newsTitles.join("; ")
        );
        parts.push("");
      }
      parts.push(
        "I can connect this to your topic, draft a summary page, or turn headlines into a task plan. Say what you want next."
      );
      return parts.join("\n");
    }
  } catch {
    /* fall through */
  }
  return (
    `Live-mode brief (${now}):\n` +
    `I couldn't reach an external live feed just now, so I'll answer from general knowledge and be explicit about uncertainty.\n` +
    `Your topic: “${prompt.slice(0, 200)}”. Ask me to refresh, or name a specific source you want me to use.`
  );
}

function chatReply(prompt: string, toolContext?: string | null): string {
  const q = prompt.trim();
  if (/what (are|is) you|who are you/i.test(q)) {
    return (
      "I'm **Neuriy AI** in ChatBase — I can chat normally, build HTML pages, draw SVG images, " +
      "plan tasks, talk about live topics, and use the Neuriy Marketplace when useful. What should we do?"
    );
  }
  if (toolContext) {
    return (
      `Here's what I put together for you.\n\n` +
      `You asked: “${q.slice(0, 240)}”\n\n` +
      `I used Marketplace context where relevant and answered in plain language. ` +
      `Ask me to refine, expand, or turn this into a page/image/task plan.`
    );
  }
  return (
    `Got it — “${q.slice(0, 280)}”\n\n` +
    `Here's a direct Neuriy take: I can help with conversation, code, HTML pages, SVG illustrations, ` +
    `task plans, and Marketplace lookups. Tell me the outcome you want and I'll produce it (not just describe it).`
  );
}

function slugify(s: string): string {
  return (
    String(s)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 48) || "neuriy"
  );
}

export async function runLocalAgent(opts: {
  prompt: string;
  model?: string;
  toolContext?: string | null;
  marketplaceUnavailable?: boolean;
  ellofiveUnavailable?: boolean;
  toolData?: unknown;
}): Promise<AgentResult> {
  const intent = detectIntent(opts.prompt);
  const artifacts: AgentArtifact[] = [];
  let reply = "";

  switch (intent) {
    case "greet":
      reply =
        "Hi — I'm Neuriy. Talk normally, or ask me to make an HTML page, draw an SVG image, plan a task, or check live topics.";
      break;
    case "html": {
      const art = buildHtmlPage(opts.prompt);
      artifacts.push(art);
      reply =
        `I built an HTML page for you: **${art.title}**.\n\n` +
        `Open the artifact below (or save \`${art.filename}\`). Want a different style, more sections, or a matching SVG hero?`;
      break;
    }
    case "image": {
      const art = buildSvgImage(opts.prompt);
      artifacts.push(art);
      reply =
        `I generated an SVG illustration: **${art.title}**.\n\n` +
        `You can download \`${art.filename}\` or ask me to tweak colors, layout, or text.`;
      break;
    }
    case "task": {
      const art = buildTaskPlan(opts.prompt);
      artifacts.push(art);
      reply =
        `I drafted a concrete task plan for **${topicFrom(opts.prompt)}** and started structuring the work.\n\n` +
        `Say “do step 1” and I'll execute the next action (page, image, code, or Marketplace lookup).`;
      break;
    }
    case "live": {
      const brief = await fetchLiveBrief(opts.prompt);
      reply = brief;
      artifacts.push({
        type: "markdown",
        title: "Live brief",
        filename: "live-brief.md",
        content: brief,
      });
      break;
    }
    case "code":
      reply =
        `Here's a practical code-oriented reply for: “${opts.prompt.slice(0, 160)}”\n\n` +
        "```typescript\n" +
        "export function handleRequest(input: string): string {\n" +
        "  const trimmed = input.trim();\n" +
        "  if (!trimmed) throw new Error('empty');\n" +
        "  return `Neuriy processed: ${trimmed.slice(0, 120)}`;\n" +
        "}\n" +
        "```\n\n" +
        "Want this as a Next.js route, a full HTML demo, or tests next?";
      break;
    case "marketplace":
      reply = formatMarketplaceAnswer(opts.prompt, opts.toolData, opts.toolContext);
      break;
    default:
      reply = chatReply(opts.prompt, opts.toolContext);
  }

  if (opts.marketplaceUnavailable) {
    reply =
      "Marketplace temporarily unavailable.\n\n" +
      "The AI can still answer using its available knowledge, but Marketplace data could not be retrieved for this request.\n\n" +
      reply;
  }

  if (opts.model === "reasoning" || opts.model === "code") {
    reply = `_(mode: ${opts.model})_\n\n` + reply;
  }

  return {
    reply,
    artifacts,
    intent,
    provider: "neuriy-local-agent",
  };
}

function formatMarketplaceAnswer(
  prompt: string,
  toolData: unknown,
  toolContext?: string | null
): string {
  const apps = Array.isArray(toolData) ? toolData : [];
  if (apps.length) {
    const lines = apps.slice(0, 8).map((a: Record<string, unknown>, i: number) => {
      const title = String(a.title || a.name || a.id || "App");
      const summary = String(a.summary || a.description || "").slice(0, 140);
      const category = String(a.category || "");
      return `${i + 1}. **${title}**${category ? ` · ${category}` : ""}${summary ? ` — ${summary}` : ""} (from Marketplace: ${title})`;
    });
    return (
      `I searched the Neuriy Marketplace for “${prompt.slice(0, 120)}” and found these matches:\n\n` +
      lines.join("\n") +
      `\n\nWant details on one of them, or should I open the best match?`
    );
  }
  if (toolContext) {
    return (
      `I queried the Marketplace for “${prompt.slice(0, 120)}”.\n\n` +
      `No strong app matches came back. Try a broader category (Assistants, Developer Tools, Creative) or another keyword.`
    );
  }
  return "I can search the Neuriy Marketplace for apps. Tell me what you need (e.g. coding assistant, creative tools).";
}

/** Embed artifacts into the chat reply so the UI shows them without extra infra. */
export function formatArtifactsForChat(artifacts: AgentArtifact[]): string {
  if (!artifacts.length) return "";
  const parts: string[] = ["", "---", "**Artifacts**"];
  for (const a of artifacts) {
    parts.push(`### ${a.title}`);
    if (a.type === "svg") {
      parts.push("```svg");
      parts.push(a.content);
      parts.push("```");
    } else if (a.type === "html") {
      parts.push("```html");
      parts.push(a.content);
      parts.push("```");
    } else {
      parts.push("```markdown");
      parts.push(a.content);
      parts.push("```");
    }
    if (a.filename) parts.push(`_File: \`${a.filename}\`_`);
  }
  return parts.join("\n");
}
